export const ERROR_CODES = {
  // Authentication
  AUTH_FAILED: "AUTH_FAILED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  ACCESS_DENIED: "ACCESS_DENIED",

  VALIDATION_FAILED: "VALIDATION_FAILED",

  INVALID_INPUT: "INVALID_INPUT",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",

  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",

  DATABASE_ERROR: "DATABASE_ERROR",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
